USE chipotle;
USE elo_db;
SELECT COUNT(*) FROM transactions;
SHOW DATABASES;
USE saas_llc;
SELECT database();
SHOW CREATE DATABASE saas_llc;
SHOW TABLES FROM saas_llc;
SHOW COLUMNS FROM churn;
SELECT COUNT(*) FROM churn;
SELECT COUNT(*) FROM transactions;
USE employees;
SHOW TABLES FROM employees;
SHOW tables;
SHOW CREATE table dept_manager;
USE albums_db;
SHOW tables;
SELECT COUNT(*) FROM albums;

SELECT * FROM albums;
SELECT COUNT(DISTINCT (artist)) FROM albums;
SHOW CREATE table albums;
SELECT MAX(release_date) FROM albums;
SELECT MIN(release_date) FROM albums;
SELECT name FROM albums WHERE artist = 'Pink Floyd';
SELECT release_date FROM albums WHERE name = 'Sgt. Pepper''s Lonely Hearts Club Band';
SELECT * FROM albums;
SELECT * FROM albums WHERE name = 'Sgt. Pepper''s Lonely Hearts Club Band';
SELECT genre FROM albums WHERE name = 'Nevermind';
SELECT name FROM albums WHERE release_date LIKE '199_';
SELECT name FROM albums WHERE sales < 20;
SELECT name FROM albums WHERE genre LIKE 'ROCK';
USE employees;
SHOW tables;
SHOW columns FROM employees;
SELECT * FROM employees LIMIT 10;
SELECT first_name, last_name FROM employees WHERE first_name IN ('Irena', 'Vidya', 'Maya');
SELECT first_name, last_name FROM employees WHERE first_name IN ('Irena') OR first_name IN ('Vidya') OR first_name IN ('Maya');
SELECT gender, first_name, last_name FROM employees WHERE (first_name = 'Irena' OR first_name = 'Vidya' OR first_name = 'Maya') AND gender = 'M';
SELECT first_name, last_name FROM employees WHERE last_name LIKE 'E%';
SELECT first_name, last_name FROM employees WHERE last_name LIKE 'E%' OR last_name LIKE '%E';
SELECT COUNT(*) FROM employees WHERE last_name LIKE '%E' AND last_name NOT LIKE 'E%';
SHOW columns FROM employees;
USE epmloyees;
SELECT hire_date, first_name, last_name FROM employees WHERE hire_date LIKE '199%';
SELECT COUNT(*) FROM employees WHERE hire_date LIKE '199%';
SELECT * FROM employees LIMIT 10;
SELECT birth_date, first_name, last_name FROM employees WHERE birth_date LIKE '%12-24';
SELECT * FROM employees WHERE birth_date LIKE '%12-24' AND hire_date LIKE '199%';
